version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'demo'
    ports:
      - "3306:3306"
    expose:
      - '3306'